# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chatify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chatify
  pod 'Alamofire', '~> 4.3'
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'ChatifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
